-- =====================================================
-- AML-EDD 反洗钱尽调存证链管理平台
-- 农业银行300号文件接口格式数据库建表和数据生成程序
-- 版本: v1.0
-- 创建时间: 2025-11-09
-- 功能: 创建符合300号文件格式的完整数据结构和测试数据
-- 数据规模: 1000个个人客户, 100个企业客户, 10000条交易记录
-- 编码: UTF-8, 支持简体中文
-- =====================================================

-- 底层参数设置
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET sql_mode = 'STRICT_ALL_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO';

-- 创建数据库（如果不存在）
CREATE DATABASE IF NOT EXISTS aml_edd_v06
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_unicode_ci;

USE aml_edd_v06;

-- =====================================================
-- 第一部分: 基础数据表结构
-- =====================================================

-- 1) 机构对照表
DROP TABLE IF EXISTS tb_bank;
CREATE TABLE tb_bank (
  Head_no       VARCHAR(20)  NOT NULL COMMENT '报告机构编码',
  Bank_code1    VARCHAR(20)  NOT NULL COMMENT '机构网点代码（PBoC机构网点代码口径）',
  Bank_code2    VARCHAR(16)  NULL COMMENT '金融机构编码（14位金融标准化编码）',
  Bank_name     VARCHAR(120) NOT NULL COMMENT '机构名称（与Bank_code1/Bank_code2对应）',
  Bord_type     CHAR(2)      NOT NULL DEFAULT '10' COMMENT '跨境标识：10境内；11境外',
  PRIMARY KEY (Bank_code1),
  UNIQUE KEY uk_tb_bank_code2 (Bank_code2),
  KEY idx_tb_bank_head (Head_no)
) COMMENT='机构对照表';

-- 2) 业务类型对照表
DROP TABLE IF EXISTS tb_settle_type;
CREATE TABLE tb_settle_type (
  Head_no     VARCHAR(20)  NOT NULL DEFAULT 'ABC001' COMMENT '报告机构编码',
  Settle_type VARCHAR(20)  NOT NULL COMMENT '业务类型编码（系统内数据字典编码）',
  Name        VARCHAR(100) NOT NULL COMMENT '业务名称（编码对应中文名）',
  PRIMARY KEY (Settle_type),
  KEY idx_settle_head (Head_no)
) COMMENT='业务类型对照表';

-- 3) 存量个人客户身份信息
DROP TABLE IF EXISTS tb_cst_pers;
CREATE TABLE tb_cst_pers (
  Head_no      VARCHAR(20)  NOT NULL DEFAULT 'ABC001' COMMENT '报告机构编码',
  Bank_code1   VARCHAR(20)  NOT NULL COMMENT '客户号归属机构网点代码，指向tb_bank',
  Cst_no       VARCHAR(50)  NOT NULL COMMENT '客户号',
  Open_time    CHAR(8)      NOT NULL COMMENT '创建日期YYYYMMDD',
  Close_time   CHAR(8)      NULL COMMENT '结束日期YYYYMMDD（销号日）',
  Acc_name     VARCHAR(40)  NOT NULL COMMENT '客户姓名',
  Cst_sex      CHAR(2)      NOT NULL COMMENT '性别：11男；12女',
  Nation       VARCHAR(20)  NOT NULL COMMENT '国籍/地区（GB/T2659-2000缩写）',
  Id_type      CHAR(2)      NOT NULL COMMENT '证件种类（11身份证…14护照…19其他）',
  Id_no        VARCHAR(50)  NOT NULL COMMENT '证件号码',
  Id_deadline  CHAR(8)      NOT NULL COMMENT '证件有效期至（长期99991231）',
  Occupation   VARCHAR(80)  NULL COMMENT '职业（如使用代码需转文字）',
  Income       DECIMAL(16,2) NULL COMMENT '年收入（元）',
  Contact1     VARCHAR(20)  NULL COMMENT '联系方式1（手机或固话）',
  Contact2     VARCHAR(20)  NULL COMMENT '联系方式2',
  Contact3     VARCHAR(20)  NULL COMMENT '联系方式3',
  Address1     VARCHAR(500) NULL COMMENT '住所地/工作单位地址',
  Address2     VARCHAR(500) NULL COMMENT '其他住所/单位地址1',
  Address3     VARCHAR(500) NULL COMMENT '其他住所/单位地址2',
  Company      VARCHAR(120) NULL COMMENT '工作单位名称',
  Sys_name     VARCHAR(120) NULL COMMENT '采集系统名称（多系统以;分隔）',
  PRIMARY KEY (Cst_no),
  KEY idx_cstpers_bank (Bank_code1),
  KEY idx_cstpers_id (Id_no),
  KEY idx_cstpers_combo (Id_no, Id_type, Cst_sex),
  KEY idx_cstpers_head (Head_no),
  CONSTRAINT fk_cstpers_bank FOREIGN KEY (Bank_code1) REFERENCES tb_bank(Bank_code1)
) COMMENT='存量个人客户身份信息表';

-- 4) 存量单位客户身份信息
DROP TABLE IF EXISTS tb_cst_unit;
CREATE TABLE tb_cst_unit (
  Head_no      VARCHAR(20)  NOT NULL DEFAULT 'ABC001' COMMENT '报告机构编码',
  Bank_code1   VARCHAR(20)  NOT NULL COMMENT '客户号归属机构网点代码，指向tb_bank',
  Cst_no       VARCHAR(50)  NOT NULL COMMENT '客户号',
  Open_time    CHAR(8)      NOT NULL COMMENT '创建日期YYYYMMDD',
  Acc_name     VARCHAR(120) NOT NULL COMMENT '客户名称（单位名称）',
  Rep_name     VARCHAR(40)  NULL COMMENT '法定代表人/负责人姓名',
  Ope_name     VARCHAR(40)  NULL COMMENT '授权经办人姓名',
  License      VARCHAR(50)  NULL COMMENT '单位证照号',
  Id_deadline  CHAR(8)      NULL COMMENT '证照有效期至（长期99991231）',
  Industry     VARCHAR(80)  NULL COMMENT '行业（如代码需转文字）',
  Reg_amt      DECIMAL(18,2) NULL COMMENT '注册资本金',
  Reg_amt_code CHAR(3)      NULL COMMENT '注册资本金币种（RMB/USD等国标）',
  Sys_name     VARCHAR(120) NULL COMMENT '采集系统名称（多系统以;分隔）',
  PRIMARY KEY (Cst_no),
  KEY idx_cstunit_bank (Bank_code1),
  KEY idx_cstunit_repname (Rep_name),
  KEY idx_cstunit_opename (Ope_name),
  KEY idx_cstunit_license (License),
  KEY idx_cstunit_head (Head_no),
  CONSTRAINT fk_cstunit_bank FOREIGN KEY (Bank_code1) REFERENCES tb_bank(Bank_code1)
) COMMENT='存量单位客户身份信息表';

-- 5) 账户主档
DROP TABLE IF EXISTS tb_acc;
CREATE TABLE tb_acc (
  Head_no       VARCHAR(20)  NOT NULL DEFAULT 'ABC001' COMMENT '报告机构编码',
  Bank_code1    VARCHAR(20)  NOT NULL COMMENT '开户行机构网点代码，指向tb_bank',
  Self_acc_name VARCHAR(120) NOT NULL COMMENT '账户户名（个人/单位）',
  Acc_state     CHAR(2)      NOT NULL DEFAULT '11' COMMENT '账户状态：11正常；12其他',
  Self_acc_no   VARCHAR(40)  NOT NULL PRIMARY KEY COMMENT '账号（若仅有卡号则同卡号）',
  Card_no       VARCHAR(40)  NULL COMMENT '卡号（可1账号多卡，多行表示映射）',
  Acc_type      CHAR(2)      NOT NULL COMMENT '公私标识：11个人；12单位',
  Acc_type1     CHAR(2)      NULL COMMENT '个人账户种类：11 I类；12 II类；13 III类；14信用卡',
  Id_no         VARCHAR(50)  NOT NULL COMMENT '证件号：个人按表3; 单位按表4 License口径',
  Cst_no        VARCHAR(50)  NOT NULL COMMENT '客户号',
  Open_time     CHAR(8)      NOT NULL COMMENT '开户日期',
  Close_time    CHAR(8)      NULL COMMENT '销户日期',
  Agency_flag   CHAR(2)      NULL COMMENT '开户是否代理：11代理；12本人',
  Acc_flag      CHAR(2)      NULL COMMENT '账户性质/是否特殊',
  Fixed_flag    CHAR(2)      NULL COMMENT '是否定期/冻结标志',
  KEY idx_acc_bank (Bank_code1),
  KEY idx_acc_cst (Cst_no),
  KEY idx_acc_open1 (Open_time, Acc_type, Cst_no),
  KEY idx_acc_open2 (Open_time, Acc_type, Id_no),
  KEY idx_acc_open3 (Open_time, Self_acc_no, Close_time),
  KEY idx_acc_agency (Open_time, Agency_flag),
  KEY idx_acc_flag1 (Self_acc_no, Acc_flag),
  KEY idx_acc_flag2 (Self_acc_no, Fixed_flag),
  KEY idx_acc_id (Id_no, Self_acc_no),
  KEY idx_acc_head (Head_no),
  CONSTRAINT fk_acc_bank FOREIGN KEY (Bank_code1) REFERENCES tb_bank(Bank_code1)
) COMMENT='符合特定条件的银行账户信息表（主档）';

-- 6) 非贷记账户交易（本外币）
DROP TABLE IF EXISTS tb_acc_txn;
CREATE TABLE tb_acc_txn (
  Date          CHAR(8)      NOT NULL COMMENT '交易日期YYYYMMDD',
  Time          CHAR(6)      NOT NULL COMMENT '交易时间HHMMSS',
  Self_bank_code VARCHAR(20) NOT NULL COMMENT '交易行代码=tb_bank.Bank_code1',
  Acc_type      CHAR(2)      NOT NULL COMMENT '公私标识：11个人；12单位',
  Cst_no        VARCHAR(50)  NOT NULL COMMENT '客户号',
  Id_no         VARCHAR(50)  NOT NULL COMMENT '证件号（个人按表3；单位按表4 License）',
  Self_acc_no   VARCHAR(40)  NOT NULL COMMENT '我方账号（不能为空）',
  Card_no       VARCHAR(40)  NULL COMMENT '我方卡号',
  Part_acc_no   VARCHAR(60)  NULL COMMENT '对手账号/卡号',
  Part_acc_name VARCHAR(120) NULL COMMENT '对手账户名称',
  Lend_flag     CHAR(2)      NOT NULL COMMENT '收付标识：10收；11付（客户角度）',
  Tsf_flag      CHAR(2)      NOT NULL COMMENT '现金/转账：10现金；11转账（客户角度）',
  Cur           CHAR(3)      NOT NULL COMMENT '币种（GB/T12406-2008）',
  Org_amt       DECIMAL(16,2) NOT NULL COMMENT '原币种交易金额',
  Usd_amt       DECIMAL(16,2) NOT NULL COMMENT '折美元交易金额',
  Rmb_amt       DECIMAL(16,2) NOT NULL COMMENT '折人民币交易金额',
  Balance       DECIMAL(16,2) NULL COMMENT '交易后账户原币种余额',
  Agency_flag   CHAR(2)      NULL COMMENT '是否代理：11代理；12本人',
  Agent_name    VARCHAR(60)  NULL COMMENT '代理人姓名（代理时填）',
  Agent_tel     VARCHAR(60)  NULL COMMENT '代理人联系方式（代理时填）',
  Agent_type    CHAR(2)      NULL COMMENT '代理人证件种类（11身份证…）',
  Agent_no      VARCHAR(50)  NULL COMMENT '代理人证件号码',
  Reverse_flag  CHAR(2)      NOT NULL DEFAULT '10' COMMENT '冲账标识：10否；11是',
  Purpose       VARCHAR(120) NULL COMMENT '摘要/用途',
  Bord_flag     CHAR(2)      NULL DEFAULT '12' COMMENT '跨境标识：11是；12否',
  Nation        VARCHAR(20)  NULL COMMENT '对方国家/地区（跨境=11时填，GB/T2659-2000）',
  Bank_flag     CHAR(2)      NULL COMMENT '交易方式：11网银；12手机；13柜面；14ATM；15其他',
  Ip_code       VARCHAR(17)  NULL COMMENT 'IP地址（网银等口径）',
  Atm_code      VARCHAR(30)  NULL COMMENT 'ATM机具编号（ATM时）',
  Bank_code     VARCHAR(20)  NULL COMMENT 'ATM机具所属行行号=tb_bank.Bank_code1',
  Mac_info      VARCHAR(17)  NULL COMMENT 'MAC/IMEI（PC/移动端）',
  Settle_type   VARCHAR(20)  NULL COMMENT '业务类型编码（指向tb_settle_type）',
  Ticd          VARCHAR(40)  NULL COMMENT '业务流水号',
  PRIMARY KEY (Date, Time, Self_acc_no, Lend_flag, Tsf_flag),
  KEY idx_txn_bank (Self_bank_code),
  KEY idx_txn_acc1 (Date, Self_acc_no, Reverse_flag, Tsf_flag, Lend_flag),
  KEY idx_txn_acc2 (Date, Cst_no,  Reverse_flag, Tsf_flag, Lend_flag),
  KEY idx_txn_acc3 (Date, Bank_flag, Self_acc_no),
  KEY idx_txn_acc4 (Date, Acc_type, Self_acc_no),
  KEY idx_txn_acc5 (Date, Self_acc_no, Part_acc_no),
  KEY idx_txn_acc6 (Date, Ip_code, Self_acc_no),
  KEY idx_txn_acc7 (Date, Id_no),
  CONSTRAINT fk_txn_bank FOREIGN KEY (Self_bank_code) REFERENCES tb_bank(Bank_code1),
  CONSTRAINT fk_txn_settle FOREIGN KEY (Settle_type) REFERENCES tb_settle_type(Settle_type)
) COMMENT='基于客户账户的交易数据表（非贷记账户）';

-- 7) 历次风险等级划分
DROP TABLE IF EXISTS tb_risk_his;
CREATE TABLE tb_risk_his (
  Bank_code1 VARCHAR(20) NOT NULL COMMENT '机构网点代码=tb_bank.Bank_code1',
  Cst_no     VARCHAR(50) NOT NULL COMMENT '客户号',
  Self_acc_name VARCHAR(120) NULL COMMENT '客户名称',
  Id_no      VARCHAR(50) NOT NULL COMMENT '证件号：个人表3；单位表4 License',
  Acc_type   CHAR(2)     NOT NULL COMMENT '公私：11个人；12单位',
  Risk_code  CHAR(2)     NOT NULL COMMENT '风险等级（10高…14低，或按五级扩展）',
  Time       CHAR(8)     NOT NULL COMMENT '划分日期（若"系统先评再人工确认"，填确认日）',
  Norm       VARCHAR(500) NULL COMMENT '划分依据/评分分值或评定理由',
  PRIMARY KEY (Cst_no, Time),
  KEY idx_riskhis_bank (Bank_code1),
  KEY idx_riskhis_time (Time),
  CONSTRAINT fk_riskhis_bank FOREIGN KEY (Bank_code1) REFERENCES tb_bank(Bank_code1)
) COMMENT='检查期内历次风险等级记录';

-- 8) 最新一次风险等级
DROP TABLE IF EXISTS tb_risk_new;
CREATE TABLE tb_risk_new (
  Bank_code1 VARCHAR(20) NOT NULL COMMENT '机构网点代码=tb_bank.Bank_code1',
  Cst_no     VARCHAR(50) NOT NULL COMMENT '客户号',
  Self_acc_name VARCHAR(120) NULL COMMENT '客户名称',
  Id_no      VARCHAR(50) NOT NULL COMMENT '证件号',
  Acc_type   CHAR(2)     NOT NULL COMMENT '公私：11个人；12单位',
  Risk_code  CHAR(2)     NOT NULL COMMENT '风险等级（同口径）',
  Time       CHAR(8)     NOT NULL COMMENT '最新一次划分日期',
  Norm       VARCHAR(500) NULL COMMENT '划分依据/理由',
  PRIMARY KEY (Cst_no),
  KEY idx_risknew_combo1 (Time, Id_no),
  KEY idx_risknew_combo2 (Cst_no, Time, Risk_code),
  KEY idx_risknew_bank (Bank_code1),
  CONSTRAINT fk_risknew_bank FOREIGN KEY (Bank_code1) REFERENCES tb_bank(Bank_code1)
) COMMENT='存量客户最新风险等级划分';

-- =====================================================
-- 第二部分: 基础数据初始化
-- =====================================================

-- 清空所有表数据
TRUNCATE TABLE tb_risk_new;
TRUNCATE TABLE tb_risk_his;
TRUNCATE TABLE tb_acc_txn;
TRUNCATE TABLE tb_acc;
TRUNCATE TABLE tb_cst_unit;
TRUNCATE TABLE tb_cst_pers;
TRUNCATE TABLE tb_settle_type;
TRUNCATE TABLE tb_bank;

-- 插入机构基础数据
INSERT INTO tb_bank (Head_no, Bank_code1, Bank_code2, Bank_name, Bord_type) VALUES
('ABC001', '103100000019', '104100000004', '中国农业银行总行营业部', '10'),
('ABC002', '103100000027', '104100000012', '中国农业银行北京分行营业部', '10'),
('ABC003', '103100000035', '104100000020', '中国农业银行上海分行营业部', '10'),
('ABC004', '103100000043', '104100000038', '中国农业银行广东分行营业部', '10'),
('ABC005', '103100000050', '104100000045', '中国农业银行深圳分行营业部', '10'),
('ABC006', '103100000068', '104100000052', '中国农业银行杭州分行营业部', '10'),
('ABC007', '103100000076', '104100000060', '中国农业银行南京分行营业部', '10'),
('ABC008', '103100000084', '104100000078', '中国农业银行成都分行营业部', '10'),
('ABC009', '103100000092', '104100000086', '中国农业银行武汉分行营业部', '10'),
('ABC010', '103100000100', '104100000094', '中国农业银行西安分行营业部', '10');

-- 插入业务类型数据
INSERT INTO tb_settle_type (Head_no, Settle_type, Name) VALUES
('ABC001', 'ST001', '存款业务'),
('ABC001', 'ST002', '取款业务'),
('ABC001', 'ST003', '转账业务'),
('ABC001', 'ST004', '汇款业务'),
('ABC001', 'ST005', '消费业务'),
('ABC001', 'ST006', '代收代付'),
('ABC001', 'ST007', '贷款发放'),
('ABC001', 'ST008', '贷款还款'),
('ABC001', 'ST009', '投资理财'),
('ABC001', 'ST010', '外汇买卖'),
('ABC001', 'ST011', '跨境汇款'),
('ABC001', 'ST012', '现金兑换'),
('ABC001', 'ST013', '票据业务'),
('ABC001', 'ST014', '担保业务'),
('ABC001', 'ST015', '其他业务');

-- =====================================================
-- 第三部分: 模拟数据生成程序
-- =====================================================

-- 创建随机数据生成函数
DELIMITER //

-- 生成随机中文名字的函数
DROP FUNCTION IF EXISTS gen_chinese_name //
CREATE FUNCTION gen_chinese_name()
RETURNS VARCHAR(40)
READS SQL DATA
DETERMINISTIC
BEGIN
  DECLARE first_name VARCHAR(20);
  DECLARE last_name VARCHAR(20);
  DECLARE first_names VARCHAR(500) DEFAULT '李,王,张,刘,陈,杨,赵,黄,周,吴,徐,孙,胡,朱,高,林,何,郭,马,罗';
  DECLARE last_names_male VARCHAR(500) DEFAULT '伟,芳,娜,秀英,敏,静,丽,强,磊,军,洋,勇,艳,杰,娟,涛,明,超,秀兰,霞';
  DECLARE last_names_female VARCHAR(500) DEFAULT '秀英,桂英,燕,玲,红,琴,兰,萍,华,蓉,梅,慧,婷,洁,莉,颖,琳,芳,玉,凤';
  DECLARE name_list VARCHAR(1000);
  DECLARE pos INT;

  -- 随机选择姓氏
  SET pos = FLOOR(1 + RAND() * 20);
  SET first_name = TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(first_names, ',', pos), ',', -1));

  -- 随机选择名字
  SET name_list = CONCAT(last_names_male, ',', last_names_female);
  SET pos = FLOOR(1 + RAND() * 40);
  SET last_name = TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(name_list, ',', pos), ',', -1));

  RETURN CONCAT(first_name, last_name);
END //

-- 生成随机身份证号码的函数
DROP FUNCTION IF EXISTS gen_id_card //
CREATE FUNCTION gen_id_card()
RETURNS VARCHAR(50)
READS SQL DATA
DETERMINISTIC
BEGIN
  DECLARE area_code VARCHAR(6) DEFAULT '110101'; -- 北京市东城区
  DECLARE birth_date CHAR(8);
  DECLARE sequence_num VARCHAR(3);
  DECLARE check_code CHAR(1);
  DECLARE id_card VARCHAR(18);
  DECLARE weights VARCHAR(17) DEFAULT '71,9,10,5,8,4,2,1,6,3,7,9,10,5,8,4,2';
  DECLARE check_codes VARCHAR(11) DEFAULT '10X98765432';
  DECLARE sum_weight INT DEFAULT 0;
  DECLARE i INT DEFAULT 1;
  DECLARE weight_val INT;
  DECLARE char_val INT;

  -- 生成随机的出生日期（1960-2000年）
  SET birth_date = LPAD(CONCAT(1960 + FLOOR(RAND() * 41),
                               LPAD(1 + FLOOR(RAND() * 12), 2, '0'),
                               LPAD(1 + FLOOR(RAND() * 28), 2, '0')), 8, '0');

  -- 生成3位顺序码
  SET sequence_num = LPAD(FLOOR(RAND() * 1000), 3, '0');

  -- 组合17位
  SET id_card = CONCAT(area_code, birth_date, sequence_num);

  -- 计算校验码
  WHILE i <= 17 DO
    SET weight_val = CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(weights, ',', i), ',', -1) AS UNSIGNED);
    SET char_val = CAST(SUBSTRING(id_card, i, 1) AS UNSIGNED);
    SET sum_weight = sum_weight + (weight_val * char_val);
    SET i = i + 1;
  END WHILE;

  SET check_code = SUBSTRING(check_codes, (sum_weight % 11) + 1, 1);
  SET id_card = CONCAT(id_card, check_code);

  RETURN id_card;
END //

-- 生成随机手机号码的函数
DROP FUNCTION IF EXISTS gen_phone_number //
CREATE FUNCTION gen_phone_number()
RETURNS VARCHAR(20)
READS SQL DATA
DETERMINISTIC
BEGIN
  DECLARE prefixes VARCHAR(50) DEFAULT '130,131,132,133,134,135,136,137,138,139,150,151,152,153,155,156,157,158,159,180,181,182,183,184,185,186,187,188,189';
  DECLARE prefix VARCHAR(3);
  DECLARE pos INT;
  DECLARE suffix VARCHAR(8);

  SET pos = FLOOR(1 + RAND() * 29);
  SET prefix = TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(prefixes, ',', pos), ',', -1));
  SET suffix = LPAD(FLOOR(RAND() * 100000000), 8, '0');

  RETURN CONCAT(prefix, suffix);
END //

-- 生成随机公司名称的函数
DROP FUNCTION IF EXISTS gen_company_name //
CREATE FUNCTION gen_company_name()
RETURNS VARCHAR(120)
READS SQL DATA
DETERMINISTIC
BEGIN
  DECLARE company_types VARCHAR(200) DEFAULT '科技有限公司,贸易有限公司,实业有限公司,投资有限公司,咨询有限公司,建设工程有限公司,信息技术有限公司,电子商务有限公司';
  DECLARE company_prefixes VARCHAR(200) DEFAULT '北京,上海,广州,深圳,杭州,南京,武汉,成都,西安,重庆';
  DECLARE company_names VARCHAR(500) DEFAULT '华强,金鼎,华润,中信,光大,招商,民生,平安,华为,腾讯,阿里巴巴,百度,京东,小米,海尔,美的,格力,万科,万达,恒大';

  DECLARE prefix VARCHAR(10);
  DECLARE name VARCHAR(20);
  DECLARE type VARCHAR(20);
  DECLARE pos INT;

  -- 随机选择地区前缀
  SET pos = FLOOR(1 + RAND() * 10);
  SET prefix = TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(company_prefixes, ',', pos), ',', -1));

  -- 随机选择公司名称
  SET pos = FLOOR(1 + RAND() * 20);
  SET name = TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(company_names, ',', pos), ',', -1));

  -- 随机选择公司类型
  SET pos = FLOOR(1 + RAND() * 8);
  SET type = TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(company_types, ',', pos), ',', -1));

  RETURN CONCAT(prefix, name, type);
END //

-- 生成统一社会信用代码的函数
DROP FUNCTION IF EXISTS gen_credit_code //
CREATE FUNCTION gen_credit_code()
RETURNS VARCHAR(50)
READS SQL DATA
DETERMINISTIC
BEGIN
  DECLARE code_part VARCHAR(17);
  DECLARE check_code CHAR(1);
  DECLARE chars VARCHAR(36) DEFAULT '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  DECLARE weights VARCHAR(34) DEFAULT '1,3,9,27,19,26,16,17,20,29,25,13,8,24,10,30,28';
  DECLARE sum_weight INT DEFAULT 0;
  DECLARE i INT DEFAULT 1;
  DECLARE char_val INT;
  DECLARE weight_val INT;

  -- 生成17位代码
  SET code_part = '';
  WHILE i <= 17 DO
    SET char_val = FLOOR(RAND() * 36);
    SET code_part = CONCAT(code_part, SUBSTRING(chars, char_val + 1, 1));
    SET i = i + 1;
  END WHILE;

  -- 计算校验码
  SET i = 1;
  WHILE i <= 17 DO
    SET char_val = LOCATE(SUBSTRING(code_part, i, 1), chars) - 1;
    SET weight_val = CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(weights, ',', i), ',', -1) AS UNSIGNED);
    SET sum_weight = sum_weight + (char_val * weight_val);
    SET i = i + 1;
  END WHILE;

  SET check_code = SUBSTRING(chars, (31 - (sum_weight % 31)) + 1, 1);

  RETURN CONCAT(code_part, check_code);
END //

DELIMITER ;

-- =====================================================
-- 第四部分: 插入个人客户数据（1000条记录）
-- =====================================================

-- 生成个人客户数据
INSERT INTO tb_cst_pers (
    Head_no, Bank_code1, Cst_no, Open_time, Close_time, Acc_name,
    Cst_sex, Nation, Id_type, Id_no, Id_deadline, Occupation, Income,
    Contact1, Contact2, Contact3, Address1, Address2, Address3, Company, Sys_name
)
SELECT
    'ABC001' as Head_no,
    ELT(FLOOR(1 + RAND() * 10), '103100000019', '103100000027', '103100000035', '103100000043', '103100000050', '103100000068', '103100000076', '103100000084', '103100000092', '103100000100') as Bank_code1,
    CONCAT('P', LPAD(num, 6, '0')) as Cst_no,
    DATE_FORMAT(DATE_SUB(CURRENT_DATE, INTERVAL FLOOR(RAND() * 3650) DAY), '%Y%m%d') as Open_time,
    CASE WHEN RAND() > 0.9 THEN DATE_FORMAT(DATE_SUB(CURRENT_DATE, INTERVAL FLOOR(RAND() * 365) DAY), '%Y%m%d') ELSE NULL END as Close_time,
    gen_chinese_name() as Acc_name,
    ELT(FLOOR(1 + RAND() * 2), '11', '12') as Cst_sex,
    'CHN' as Nation,
    '11' as Id_type,
    gen_id_card() as Id_no,
    CASE WHEN RAND() > 0.8 THEN '99991231' ELSE DATE_FORMAT(DATE_ADD(CURRENT_DATE, INTERVAL FLOOR(RAND() * 3650) DAY), '%Y%m%d') END as Id_deadline,
    ELT(FLOOR(1 + RAND() * 15),
        '软件工程师', '教师', '医生', '律师', '会计', '销售经理', '企业高管', '公务员',
        '工程师', '设计师', '研究员', '金融分析师', '项目经理', '市场专员', '自由职业') as Occupation,
    ROUND(RAND() * 500000 + 50000, 2) as Income,
    gen_phone_number() as Contact1,
    CASE WHEN RAND() > 0.5 THEN gen_phone_number() ELSE NULL END as Contact2,
    CASE WHEN RAND() > 0.7 THEN gen_phone_number() ELSE NULL END as Contact3,
    CONCAT(ELT(FLOOR(1 + RAND() * 34), '北京市', '上海市', '广州市', '深圳市', '杭州市', '南京市', '武汉市', '成都市', '西安市', '重庆市', '天津市', '苏州市', '青岛市', '郑州市', '长沙市', '东莞市', '佛山市', '合肥市', '大连市', '厦门市', '济南市', '无锡市', '福州市', '哈尔滨市', '长春市', '石家庄市', '常州市', '烟台市', '唐山市', '太原市', '南昌市', '南通市', '贵阳市', '南宁市'),
         ELT(FLOOR(1 + RAND() * 20), '朝阳区', '海淀区', '西城区', '东城区', '丰台区', '石景山区', '通州区', '顺义区', '昌平区', '大兴区', '房山区', '门头沟区', '怀柔区', '平谷区', '密云区', '延庆区', '浦东新区', '黄浦区', '徐汇区', '长宁区'),
         ELT(FLOOR(1 + RAND() * 10), '金融街', 'CBD商务区', '高新区', '经济开发区', '大学城', '科技园区', '工业区', '商业中心', '住宅区', '政务区'),
         ELT(FLOOR(1 + RAND() * 20), '1号', '2号', '3号', '5号', '8号', '10号', '12号', '15号', '18号', '20号', '25号', '28号', '30号', '35号', '38号', '40号', '45号', '48号', '50号', '88号'),
         ELT(FLOOR(1 + RAND() * 5), 'A座', 'B座', 'C座', 'D座', 'E座'),
         LPAD(FLOOR(1 + RAND() * 30), 2, '0'),
         '室') as Address1,
    CASE WHEN RAND() > 0.6 THEN
        CONCAT(ELT(FLOOR(1 + RAND() * 20), '北京市', '上海市', '广州市', '深圳市', '杭州市', '南京市'), '临时居住地')
    ELSE NULL END as Address2,
    CASE WHEN RAND() > 0.8 THEN
        CONCAT(ELT(FLOOR(1 + RAND() * 20), '北京市', '上海市', '广州市', '深圳市', '杭州市', '南京市'), '其他地址')
    ELSE NULL END as Address3,
    CASE WHEN RAND() > 0.4 THEN gen_company_name() ELSE NULL END as Company,
    CASE WHEN RAND() > 0.5 THEN '个人网银系统' ELSE '柜面系统' END as Sys_name
FROM (
    SELECT 1 as num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
    SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION
    SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION
    SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION
    SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION
    SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION
    SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION
    SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION
    SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION
    SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50 UNION
    SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55 UNION
    SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60 UNION
    SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65 UNION
    SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70 UNION
    SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75 UNION
    SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80 UNION
    SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84 UNION SELECT 85 UNION
    SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89 UNION SELECT 90 UNION
    SELECT 91 UNION SELECT 92 UNION SELECT 93 UNION SELECT 94 UNION SELECT 95 UNION
    SELECT 96 UNION SELECT 97 UNION SELECT 98 UNION SELECT 99 UNION SELECT 100 UNION
    SELECT 101 UNION SELECT 102 UNION SELECT 103 UNION SELECT 104 UNION SELECT 105 UNION
    SELECT 106 UNION SELECT 107 UNION SELECT 108 UNION SELECT 109 UNION SELECT 110 UNION
    SELECT 111 UNION SELECT 112 UNION SELECT 113 UNION SELECT 114 UNION SELECT 115 UNION
    SELECT 116 UNION SELECT 117 UNION SELECT 118 UNION SELECT 119 UNION SELECT 120 UNION
    SELECT 121 UNION SELECT 122 UNION SELECT 123 UNION SELECT 124 UNION SELECT 125 UNION
    SELECT 126 UNION SELECT 127 UNION SELECT 128 UNION SELECT 129 UNION SELECT 130 UNION
    SELECT 131 UNION SELECT 132 UNION SELECT 133 UNION SELECT 134 UNION SELECT 135 UNION
    SELECT 136 UNION SELECT 137 UNION SELECT 138 UNION SELECT 139 UNION SELECT 140 UNION
    SELECT 141 UNION SELECT 142 UNION SELECT 143 UNION SELECT 144 UNION SELECT 145 UNION
    SELECT 146 UNION SELECT 147 UNION SELECT 148 UNION SELECT 149 UNION SELECT 150 UNION
    SELECT 151 UNION SELECT 152 UNION SELECT 153 UNION SELECT 154 UNION SELECT 155 UNION
    SELECT 156 UNION SELECT 157 UNION SELECT 158 UNION SELECT 159 UNION SELECT 160 UNION
    SELECT 161 UNION SELECT 162 UNION SELECT 163 UNION SELECT 164 UNION SELECT 165 UNION
    SELECT 166 UNION SELECT 167 UNION SELECT 168 UNION SELECT 169 UNION SELECT 170 UNION
    SELECT 171 UNION SELECT 172 UNION SELECT 173 UNION SELECT 174 UNION SELECT 175 UNION
    SELECT 176 UNION SELECT 177 UNION SELECT 178 UNION SELECT 179 UNION SELECT 180 UNION
    SELECT 181 UNION SELECT 182 UNION SELECT 183 UNION SELECT 184 UNION SELECT 185 UNION
    SELECT 186 UNION SELECT 187 UNION SELECT 188 UNION SELECT 189 UNION SELECT 190 UNION
    SELECT 191 UNION SELECT 192 UNION SELECT 193 UNION SELECT 194 UNION SELECT 195 UNION
    SELECT 196 UNION SELECT 197 UNION SELECT 198 UNION SELECT 199 UNION SELECT 200 UNION
    SELECT 201 UNION SELECT 202 UNION SELECT 203 UNION SELECT 204 UNION SELECT 205 UNION
    SELECT 206 UNION SELECT 207 UNION SELECT 208 UNION SELECT 209 UNION SELECT 210 UNION
    SELECT 211 UNION SELECT 212 UNION SELECT 213 UNION SELECT 214 UNION SELECT 215 UNION
    SELECT 216 UNION SELECT 217 UNION SELECT 218 UNION SELECT 219 UNION SELECT 220 UNION
    SELECT 221 UNION SELECT 222 UNION SELECT 223 UNION SELECT 224 UNION SELECT 225 UNION
    SELECT 226 UNION SELECT 227 UNION SELECT 228 UNION SELECT 229 UNION SELECT 230 UNION
    SELECT 231 UNION SELECT 232 UNION SELECT 233 UNION SELECT 234 UNION SELECT 235 UNION
    SELECT 236 UNION SELECT 237 UNION SELECT 238 UNION SELECT 239 UNION SELECT 240 UNION
    SELECT 241 UNION SELECT 242 UNION SELECT 243 UNION SELECT 244 UNION SELECT 245 UNION
    SELECT 246 UNION SELECT 247 UNION SELECT 248 UNION SELECT 249 UNION SELECT 250 UNION
    SELECT 251 UNION SELECT 252 UNION SELECT 253 UNION SELECT 254 UNION SELECT 255 UNION
    SELECT 256 UNION SELECT 257 UNION SELECT 258 UNION SELECT 259 UNION SELECT 260 UNION
    SELECT 261 UNION SELECT 262 UNION SELECT 263 UNION SELECT 264 UNION SELECT 265 UNION
    SELECT 266 UNION SELECT 267 UNION SELECT 268 UNION SELECT 269 UNION SELECT 270 UNION
    SELECT 271 UNION SELECT 272 UNION SELECT 273 UNION SELECT 274 UNION SELECT 275 UNION
    SELECT 276 UNION SELECT 277 UNION SELECT 278 UNION SELECT 279 UNION SELECT 280 UNION
    SELECT 281 UNION SELECT 282 UNION SELECT 283 UNION SELECT 284 UNION SELECT 285 UNION
    SELECT 286 UNION SELECT 287 UNION SELECT 288 UNION SELECT 289 UNION SELECT 290 UNION
    SELECT 291 UNION SELECT 292 UNION SELECT 293 UNION SELECT 294 UNION SELECT 295 UNION
    SELECT 296 UNION SELECT 297 UNION SELECT 298 UNION SELECT 299 UNION SELECT 300 UNION
    SELECT 301 UNION SELECT 302 UNION SELECT 303 UNION SELECT 304 UNION SELECT 305 UNION
    SELECT 306 UNION SELECT 307 UNION SELECT 308 UNION SELECT 309 UNION SELECT 310 UNION
    SELECT 311 UNION SELECT 312 UNION SELECT 313 UNION SELECT 314 UNION SELECT 315 UNION
    SELECT 316 UNION SELECT 317 UNION SELECT 318 UNION SELECT 319 UNION SELECT 320 UNION
    SELECT 321 UNION SELECT 322 UNION SELECT 323 UNION SELECT 324 UNION SELECT 325 UNION
    SELECT 326 UNION SELECT 327 UNION SELECT 328 UNION SELECT 329 UNION SELECT 330 UNION
    SELECT 331 UNION SELECT 332 UNION SELECT 333 UNION SELECT 334 UNION SELECT 335 UNION
    SELECT 336 UNION SELECT 337 UNION SELECT 338 UNION SELECT 339 UNION SELECT 340 UNION
    SELECT 341 UNION SELECT 342 UNION SELECT 343 UNION SELECT 344 UNION SELECT 345 UNION
    SELECT 346 UNION SELECT 347 UNION SELECT 348 UNION SELECT 349 UNION SELECT 350 UNION
    SELECT 351 UNION SELECT 352 UNION SELECT 353 UNION SELECT 354 UNION SELECT 355 UNION
    SELECT 356 UNION SELECT 357 UNION SELECT 358 UNION SELECT 359 UNION SELECT 360 UNION
    SELECT 361 UNION SELECT 362 UNION SELECT 363 UNION SELECT 364 UNION SELECT 365 UNION
    SELECT 366 UNION SELECT 367 UNION SELECT 368 UNION SELECT 369 UNION SELECT 370 UNION
    SELECT 371 UNION SELECT 372 UNION SELECT 373 UNION SELECT 374 UNION SELECT 375 UNION
    SELECT 376 UNION SELECT 377 UNION SELECT 378 UNION SELECT 379 UNION SELECT 380 UNION
    SELECT 381 UNION SELECT 382 UNION SELECT 383 UNION SELECT 384 UNION SELECT 385 UNION
    SELECT 386 UNION SELECT 387 UNION SELECT 388 UNION SELECT 389 UNION SELECT 390 UNION
    SELECT 391 UNION SELECT 392 UNION SELECT 393 UNION SELECT 394 UNION SELECT 395 UNION
    SELECT 396 UNION SELECT 397 UNION SELECT 398 UNION SELECT 399 UNION SELECT 400 UNION
    SELECT 401 UNION SELECT 402 UNION SELECT 403 UNION SELECT 404 UNION SELECT 405 UNION
    SELECT 406 UNION SELECT 407 UNION SELECT 408 UNION SELECT 409 UNION SELECT 410 UNION
    SELECT 411 UNION SELECT 412 UNION SELECT 413 UNION SELECT 414 UNION SELECT 415 UNION
    SELECT 416 UNION SELECT 417 UNION SELECT 418 UNION SELECT 419 UNION SELECT 420 UNION
    SELECT 421 UNION SELECT 422 UNION SELECT 423 UNION SELECT 424 UNION SELECT 425 UNION
    SELECT 426 UNION SELECT 427 UNION SELECT 428 UNION SELECT 429 UNION SELECT 430 UNION
    SELECT 431 UNION SELECT 432 UNION SELECT 433 UNION SELECT 434 UNION SELECT 435 UNION
    SELECT 436 UNION SELECT 437 UNION SELECT 438 UNION SELECT 439 UNION SELECT 440 UNION
    SELECT 441 UNION SELECT 442 UNION SELECT 443 UNION SELECT 444 UNION SELECT 445 UNION
    SELECT 446 UNION SELECT 447 UNION SELECT 448 UNION SELECT 449 UNION SELECT 450 UNION
    SELECT 451 UNION SELECT 452 UNION SELECT 453 UNION SELECT 454 UNION SELECT 455 UNION
    SELECT 456 UNION SELECT 457 UNION SELECT 458 UNION SELECT 459 UNION SELECT 460 UNION
    SELECT 461 UNION SELECT 462 UNION SELECT 463 UNION SELECT 464 UNION SELECT 465 UNION
    SELECT 466 UNION SELECT 467 UNION SELECT 468 UNION SELECT 469 UNION SELECT 470 UNION
    SELECT 471 UNION SELECT 472 UNION SELECT 473 UNION SELECT 474 UNION SELECT 475 UNION
    SELECT 476 UNION SELECT 477 UNION SELECT 478 UNION SELECT 479 UNION SELECT 480 UNION
    SELECT 481 UNION SELECT 482 UNION SELECT 483 UNION SELECT 484 UNION SELECT 485 UNION
    SELECT 486 UNION SELECT 487 UNION SELECT 488 UNION SELECT 489 UNION SELECT 490 UNION
    SELECT 491 UNION SELECT 492 UNION SELECT 493 UNION SELECT 494 UNION SELECT 495 UNION
    SELECT 496 UNION SELECT 497 UNION SELECT 498 UNION SELECT 499 UNION SELECT 500 UNION
    SELECT 501 UNION SELECT 502 UNION SELECT 503 UNION SELECT 504 UNION SELECT 505 UNION
    SELECT 506 UNION SELECT 507 UNION SELECT 508 UNION SELECT 509 UNION SELECT 510 UNION
    SELECT 511 UNION SELECT 512 UNION SELECT 513 UNION SELECT 514 UNION SELECT 515 UNION
    SELECT 516 UNION SELECT 517 UNION SELECT 518 UNION SELECT 519 UNION SELECT 520 UNION
    SELECT 521 UNION SELECT 522 UNION SELECT 523 UNION SELECT 524 UNION SELECT 525 UNION
    SELECT 526 UNION SELECT 527 UNION SELECT 528 UNION SELECT 529 UNION SELECT 530 UNION
    SELECT 531 UNION SELECT 532 UNION SELECT 533 UNION SELECT 534 UNION SELECT 535 UNION
    SELECT 536 UNION SELECT 537 UNION SELECT 538 UNION SELECT 539 UNION SELECT 540 UNION
    SELECT 541 UNION SELECT 542 UNION SELECT 543 UNION SELECT 544 UNION SELECT 545 UNION
    SELECT 546 UNION SELECT 547 UNION SELECT 548 UNION SELECT 549 UNION SELECT 550 UNION
    SELECT 551 UNION SELECT 552 UNION SELECT 553 UNION SELECT 554 UNION SELECT 555 UNION
    SELECT 556 UNION SELECT 557 UNION SELECT 558 UNION SELECT 559 UNION SELECT 560 UNION
    SELECT 561 UNION SELECT 562 UNION SELECT 563 UNION SELECT 564 UNION SELECT 565 UNION
    SELECT 566 UNION SELECT 567 UNION SELECT 568 UNION SELECT 569 UNION SELECT 570 UNION
    SELECT 571 UNION SELECT 572 UNION SELECT 573 UNION SELECT 574 UNION SELECT 575 UNION
    SELECT 576 UNION SELECT 577 UNION SELECT 578 UNION SELECT 579 UNION SELECT 580 UNION
    SELECT 581 UNION SELECT 582 UNION SELECT 583 UNION SELECT 584 UNION SELECT 585 UNION
    SELECT 586 UNION SELECT 587 UNION SELECT 588 UNION SELECT 589 UNION SELECT 590 UNION
    SELECT 591 UNION SELECT 592 UNION SELECT 593 UNION SELECT 594 UNION SELECT 595 UNION
    SELECT 596 UNION SELECT 597 UNION SELECT 598 UNION SELECT 599 UNION SELECT 600 UNION
    SELECT 601 UNION SELECT 602 UNION SELECT 603 UNION SELECT 604 UNION SELECT 605 UNION
    SELECT 606 UNION SELECT 607 UNION SELECT 608 UNION SELECT 609 UNION SELECT 610 UNION
    SELECT 611 UNION SELECT 612 UNION SELECT 613 UNION SELECT 614 UNION SELECT 615 UNION
    SELECT 616 UNION SELECT 617 UNION SELECT 618 UNION SELECT 619 UNION SELECT 620 UNION
    SELECT 621 UNION SELECT 622 UNION SELECT 623 UNION SELECT 624 UNION SELECT 625 UNION
    SELECT 626 UNION SELECT 627 UNION SELECT 628 UNION SELECT 629 UNION SELECT 630 UNION
    SELECT 631 UNION SELECT 632 UNION SELECT 633 UNION SELECT 634 UNION SELECT 635 UNION
    SELECT 636 UNION SELECT 637 UNION SELECT 638 UNION SELECT 639 UNION SELECT 640 UNION
    SELECT 641 UNION SELECT 642 UNION SELECT 643 UNION SELECT 644 UNION SELECT 645 UNION
    SELECT 646 UNION SELECT 647 UNION SELECT 648 UNION SELECT 649 UNION SELECT 650 UNION
    SELECT 651 UNION SELECT 652 UNION SELECT 653 UNION SELECT 654 UNION SELECT 655 UNION
    SELECT 656 UNION SELECT 657 UNION SELECT 658 UNION SELECT 659 UNION SELECT 660 UNION
    SELECT 661 UNION SELECT 662 UNION SELECT 663 UNION SELECT 664 UNION SELECT 665 UNION
    SELECT 666 UNION SELECT 667 UNION SELECT 668 UNION SELECT 669 UNION SELECT 670 UNION
    SELECT 671 UNION SELECT 672 UNION SELECT 673 UNION SELECT 674 UNION SELECT 675 UNION
    SELECT 676 UNION SELECT 677 UNION SELECT 678 UNION SELECT 679 UNION SELECT 680 UNION
    SELECT 681 UNION SELECT 682 UNION SELECT 683 UNION SELECT 684 UNION SELECT 685 UNION
    SELECT 686 UNION SELECT 687 UNION SELECT 688 UNION SELECT 689 UNION SELECT 690 UNION
    SELECT 691 UNION SELECT 692 UNION SELECT 693 UNION SELECT 694 UNION SELECT 695 UNION
    SELECT 696 UNION SELECT 697 UNION SELECT 698 UNION SELECT 699 UNION SELECT 700 UNION
    SELECT 701 UNION SELECT 702 UNION SELECT 703 UNION SELECT 704 UNION SELECT 705 UNION
    SELECT 706 UNION SELECT 707 UNION SELECT 708 UNION SELECT 709 UNION SELECT 710 UNION
    SELECT 711 UNION SELECT 712 UNION SELECT 713 UNION SELECT 714 UNION SELECT 715 UNION
    SELECT 716 UNION SELECT 717 UNION SELECT 718 UNION SELECT 719 UNION SELECT 720 UNION
    SELECT 721 UNION SELECT 722 UNION SELECT 723 UNION SELECT 724 UNION SELECT 725 UNION
    SELECT 726 UNION SELECT 727 UNION SELECT 728 UNION SELECT 729 UNION SELECT 730 UNION
    SELECT 731 UNION SELECT 732 UNION SELECT 733 UNION SELECT 734 UNION SELECT 735 UNION
    SELECT 736 UNION SELECT 737 UNION SELECT 738 UNION SELECT 739 UNION SELECT 740 UNION
    SELECT 741 UNION SELECT 742 UNION SELECT 743 UNION SELECT 744 UNION SELECT 745 UNION
    SELECT 746 UNION SELECT 747 UNION SELECT 748 UNION SELECT 749 UNION SELECT 750 UNION
    SELECT 751 UNION SELECT 752 UNION SELECT 753 UNION SELECT 754 UNION SELECT 755 UNION
    SELECT 756 UNION SELECT 757 UNION SELECT 758 UNION SELECT 759 UNION SELECT 760 UNION
    SELECT 761 UNION SELECT 762 UNION SELECT 763 UNION SELECT 764 UNION SELECT 765 UNION
    SELECT 766 UNION SELECT 767 UNION SELECT 768 UNION SELECT 769 UNION SELECT 770 UNION
    SELECT 771 UNION SELECT 772 UNION SELECT 773 UNION SELECT 774 UNION SELECT 775 UNION
    SELECT 776 UNION SELECT 777 UNION SELECT 778 UNION SELECT 779 UNION SELECT 780 UNION
    SELECT 781 UNION SELECT 782 UNION SELECT 783 UNION SELECT 784 UNION SELECT 785 UNION
    SELECT 786 UNION SELECT 787 UNION SELECT 788 UNION SELECT 789 UNION SELECT 790 UNION
    SELECT 791 UNION SELECT 792 UNION SELECT 793 UNION SELECT 794 UNION SELECT 795 UNION
    SELECT 796 UNION SELECT 797 UNION SELECT 798 UNION SELECT 799 UNION SELECT 800 UNION
    SELECT 801 UNION SELECT 802 UNION SELECT 803 UNION SELECT 804 UNION SELECT 805 UNION
    SELECT 806 UNION SELECT 807 UNION SELECT 808 UNION SELECT 809 UNION SELECT 810 UNION
    SELECT 811 UNION SELECT 812 UNION SELECT 813 UNION SELECT 814 UNION SELECT 815 UNION
    SELECT 816 UNION SELECT 817 UNION SELECT 818 UNION SELECT 819 UNION SELECT 820 UNION
    SELECT 821 UNION SELECT 822 UNION SELECT 823 UNION SELECT 824 UNION SELECT 825 UNION
    SELECT 826 UNION SELECT 827 UNION SELECT 828 UNION SELECT 829 UNION SELECT 830 UNION
    SELECT 831 UNION SELECT 832 UNION SELECT 833 UNION SELECT 834 UNION SELECT 835 UNION
    SELECT 836 UNION SELECT 837 UNION SELECT 838 UNION SELECT 839 UNION SELECT 840 UNION
    SELECT 841 UNION SELECT 842 UNION SELECT 843 UNION SELECT 844 UNION SELECT 845 UNION
    SELECT 846 UNION SELECT 847 UNION SELECT 848 UNION SELECT 849 UNION SELECT 850 UNION
    SELECT 851 UNION SELECT 852 UNION SELECT 853 UNION SELECT 854 UNION SELECT 855 UNION
    SELECT 856 UNION SELECT 857 UNION SELECT 858 UNION SELECT 859 UNION SELECT 860 UNION
    SELECT 861 UNION SELECT 862 UNION SELECT 863 UNION SELECT 864 UNION SELECT 865 UNION
    SELECT 866 UNION SELECT 867 UNION SELECT 868 UNION SELECT 869 UNION SELECT 870 UNION
    SELECT 871 UNION SELECT 872 UNION SELECT 873 UNION SELECT 874 UNION SELECT 875 UNION
    SELECT 876 UNION SELECT 877 UNION SELECT 878 UNION SELECT 879 UNION SELECT 880 UNION
    SELECT 881 UNION SELECT 882 UNION SELECT 883 UNION SELECT 884 UNION SELECT 885 UNION
    SELECT 886 UNION SELECT 887 UNION SELECT 888 UNION SELECT 889 UNION SELECT 890 UNION
    SELECT 891 UNION SELECT 892 UNION SELECT 893 UNION SELECT 894 UNION SELECT 895 UNION
    SELECT 896 UNION SELECT 897 UNION SELECT 898 UNION SELECT 899 UNION SELECT 900 UNION
    SELECT 901 UNION SELECT 902 UNION SELECT 903 UNION SELECT 904 UNION SELECT 905 UNION
    SELECT 906 UNION SELECT 907 UNION SELECT 908 UNION SELECT 909 UNION SELECT 910 UNION
    SELECT 911 UNION SELECT 912 UNION SELECT 913 UNION SELECT 914 UNION SELECT 915 UNION
    SELECT 916 UNION SELECT 917 UNION SELECT 918 UNION SELECT 919 UNION SELECT 920 UNION
    SELECT 921 UNION SELECT 922 UNION SELECT 923 UNION SELECT 924 UNION SELECT 925 UNION
    SELECT 926 UNION SELECT 927 UNION SELECT 928 UNION SELECT 929 UNION SELECT 930 UNION
    SELECT 931 UNION SELECT 932 UNION SELECT 933 UNION SELECT 934 UNION SELECT 935 UNION
    SELECT 936 UNION SELECT 937 UNION SELECT 938 UNION SELECT 939 UNION SELECT 940 UNION
    SELECT 941 UNION SELECT 942 UNION SELECT 943 UNION SELECT 944 UNION SELECT 945 UNION
    SELECT 946 UNION SELECT 947 UNION SELECT 948 UNION SELECT 949 UNION SELECT 950 UNION
    SELECT 951 UNION SELECT 952 UNION SELECT 953 UNION SELECT 954 UNION SELECT 955 UNION
    SELECT 956 UNION SELECT 957 UNION SELECT 958 UNION SELECT 959 UNION SELECT 960 UNION
    SELECT 961 UNION SELECT 962 UNION SELECT 963 UNION SELECT 964 UNION SELECT 965 UNION
    SELECT 966 UNION SELECT 967 UNION SELECT 968 UNION SELECT 969 UNION SELECT 970 UNION
    SELECT 971 UNION SELECT 972 UNION SELECT 973 UNION SELECT 974 UNION SELECT 975 UNION
    SELECT 976 UNION SELECT 977 UNION SELECT 978 UNION SELECT 979 UNION SELECT 980 UNION
    SELECT 981 UNION SELECT 982 UNION SELECT 983 UNION SELECT 984 UNION SELECT 985 UNION
    SELECT 986 UNION SELECT 987 UNION SELECT 988 UNION SELECT 989 UNION SELECT 990 UNION
    SELECT 991 UNION SELECT 992 UNION SELECT 993 UNION SELECT 994 UNION SELECT 995 UNION
    SELECT 996 UNION SELECT 997 UNION SELECT 998 UNION SELECT 999 UNION SELECT 1000
) AS numbers;

-- =====================================================
-- 第五部分: 插入企业客户数据（100条记录）
-- =====================================================

-- 生成企业客户数据
INSERT INTO tb_cst_unit (
    Head_no, Bank_code1, Cst_no, Open_time, Acc_name,
    Rep_name, Ope_name, License, Id_deadline, Industry,
    Reg_amt, Reg_amt_code, Sys_name
)
SELECT
    'ABC001' as Head_no,
    ELT(FLOOR(1 + RAND() * 10), '103100000019', '103100000027', '103100000035', '103100000043', '103100000050', '103100000068', '103100000076', '103100000084', '103100000092', '103100000100') as Bank_code1,
    CONCAT('U', LPAD(num, 4, '0')) as Cst_no,
    DATE_FORMAT(DATE_SUB(CURRENT_DATE, INTERVAL FLOOR(RAND() * 3650) DAY), '%Y%m%d') as Open_time,
    gen_company_name() as Acc_name,
    gen_chinese_name() as Rep_name,
    CASE WHEN RAND() > 0.3 THEN gen_chinese_name() ELSE NULL END as Ope_name,
    gen_credit_code() as License,
    CASE WHEN RAND() > 0.7 THEN '99991231' ELSE DATE_FORMAT(DATE_ADD(CURRENT_DATE, INTERVAL FLOOR(RAND() * 3650) DAY), '%Y%m%d') END as Id_deadline,
    ELT(FLOOR(1 + RAND() * 20),
        '软件开发', '电子商务', '金融服务', '教育培训', '医疗健康', '房地产', '建筑工程',
        '制造业', '批发零售', '物流运输', '餐饮服务', '文化传媒', '能源化工', '农业', '环保科技',
        '咨询服务', '法律服务', '会计审计', '人力资源', '旅游服务') as Industry,
    ROUND(RAND() * 50000000 + 1000000, 2) as Reg_amt,
    ELT(FLOOR(1 + RAND() * 3), 'RMB', 'USD', 'EUR') as Reg_amt_code,
    CASE WHEN RAND() > 0.4 THEN '企业网银系统' ELSE '对公业务系统' END as Sys_name
FROM (
    SELECT 1 as num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
    SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION
    SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION
    SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION
    SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION
    SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION
    SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION
    SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION
    SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION
    SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50 UNION
    SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55 UNION
    SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60 UNION
    SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65 UNION
    SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70 UNION
    SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75 UNION
    SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80 UNION
    SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84 UNION SELECT 85 UNION
    SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89 UNION SELECT 90 UNION
    SELECT 91 UNION SELECT 92 UNION SELECT 93 UNION SELECT 94 UNION SELECT 95 UNION
    SELECT 96 UNION SELECT 97 UNION SELECT 98 UNION SELECT 99 UNION SELECT 100
) AS numbers;

-- =====================================================
-- 第六部分: 插入账户数据（基于个人和企业客户）
-- =====================================================

-- 为个人客户生成账户
INSERT INTO tb_acc (
    Head_no, Bank_code1, Self_acc_name, Acc_state, Self_acc_no,
    Card_no, Acc_type, Acc_type1, Id_no, Cst_no, Open_time,
    Close_time, Agency_flag, Acc_flag, Fixed_flag
)
SELECT
    'ABC001' as Head_no,
    p.Bank_code1,
    p.Acc_name as Self_acc_name,
    '11' as Acc_state,
    CONCAT('ACC', LPAD(p.Cst_no, 8, '0')) as Self_acc_no,
    CASE WHEN RAND() > 0.3 THEN CONCAT('CARD', LPAD(p.Cst_no, 8, '0')) ELSE NULL END as Card_no,
    '11' as Acc_type,
    ELT(FLOOR(1 + RAND() * 4), '11', '12', '13', '14') as Acc_type1,
    p.Id_no,
    p.Cst_no,
    p.Open_time,
    CASE WHEN RAND() > 0.95 THEN DATE_FORMAT(DATE_SUB(CURRENT_DATE, INTERVAL FLOOR(RAND() * 365) DAY), '%Y%m%d') ELSE NULL END as Close_time,
    ELT(FLOOR(1 + RAND() * 2), '11', '12') as Agency_flag,
    CASE WHEN RAND() > 0.8 THEN '11' ELSE '12' END as Acc_flag,
    CASE WHEN RAND() > 0.9 THEN '11' ELSE '12' END as Fixed_flag
FROM tb_cst_pers p
WHERE RAND() > 0.2; -- 80%的个人客户有账户

-- 为企业客户生成账户
INSERT INTO tb_acc (
    Head_no, Bank_code1, Self_acc_name, Acc_state, Self_acc_no,
    Card_no, Acc_type, Acc_type1, Id_no, Cst_no, Open_time,
    Close_time, Agency_flag, Acc_flag, Fixed_flag
)
SELECT
    'ABC001' as Head_no,
    u.Bank_code1,
    u.Acc_name as Self_acc_name,
    '11' as Acc_state,
    CONCAT('BIZ', LPAD(u.Cst_no, 6, '0')) as Self_acc_no,
    CASE WHEN RAND() > 0.5 THEN CONCAT('BCARD', LPAD(u.Cst_no, 6, '0')) ELSE NULL END as Card_no,
    '12' as Acc_type,
    NULL as Acc_type1,
    u.License,
    u.Cst_no,
    u.Open_time,
    CASE WHEN RAND() > 0.95 THEN DATE_FORMAT(DATE_SUB(CURRENT_DATE, INTERVAL FLOOR(RAND() * 365) DAY), '%Y%m%d') ELSE NULL END as Close_time,
    ELT(FLOOR(1 + RAND() * 2), '11', '12') as Agency_flag,
    CASE WHEN RAND() > 0.7 THEN '11' ELSE '12' END as Acc_flag,
    CASE WHEN RAND() > 0.8 THEN '11' ELSE '12' End as Fixed_flag
FROM tb_cst_unit u;

-- =====================================================
-- 第七部分: 插入交易数据（10000条记录）
-- =====================================================

-- 生成交易数据（使用存储过程提高性能）
DELIMITER //
DROP PROCEDURE IF EXISTS GenerateTransactions //
CREATE PROCEDURE GenerateTransactions()
BEGIN
    DECLARE i INT DEFAULT 1;
    DECLARE trans_date DATE;
    DECLARE trans_time TIME;
    DECLARE acc_count INT;
    DECLARE random_acc_index INT;
    DECLARE selected_acc_no VARCHAR(40);
    DECLARE selected_card_no VARCHAR(40);
    DECLARE selected_cst_no VARCHAR(50);
    DECLARE selected_id_no VARCHAR(50);
    DECLARE selected_acc_type CHAR(2);
    DECLARE selected_bank_code VARCHAR(20);
    DECLARE lend_flag CHAR(2);
    DECLARE tsf_flag CHAR(2);
    DECLARE currency CHAR(3);
    DECLARE amount DECIMAL(16,2);
    DECLARE usd_amount DECIMAL(16,2);
    DECLARE rmb_amount DECIMAL(16,2);
    DECLARE balance DECIMAL(16,2);
    DECLARE settlement_type VARCHAR(20);
    DECLARE bank_flag CHAR(2);
    DECLARE purpose_desc VARCHAR(120);

    -- 获取账户总数
    SELECT COUNT(*) INTO acc_count FROM tb_acc WHERE Acc_state = '11';

    WHILE i <= 10000 DO
        -- 随机选择一个账户
        SET random_acc_index = FLOOR(1 + RAND() * acc_count);

        SELECT
            a.Self_acc_no, a.Card_no, a.Cst_no, a.Id_no, a.Acc_type, a.Bank_code1
        INTO
            selected_acc_no, selected_card_no, selected_cst_no, selected_id_no, selected_acc_type, selected_bank_code
        FROM tb_acc a
        WHERE a.Acc_state = '11'
        LIMIT 1 OFFSET random_acc_index - 1;

        -- 生成随机交易日期和时间（最近90天内）
        SET trans_date = DATE_SUB(CURRENT_DATE, INTERVAL FLOOR(RAND() * 90) DAY);
        SET trans_time = TIME_FORMAT(CONCAT(
            LPAD(FLOOR(RAND() * 24), 2, '0'), ':',
            LPAD(FLOOR(RAND() * 60), 2, '0'), ':',
            LPAD(FLOOR(RAND() * 60), 2, '0')
        ), '%H:%i:%s');

        -- 随机生成交易参数
        SET lend_flag = ELT(FLOOR(1 + RAND() * 2), '10', '11'); -- 收/付
        SET tsf_flag = ELT(FLOOR(1 + RAND() * 2), '10', '11'); -- 现金/转账
        SET currency = ELT(FLOOR(1 + RAND() * 5), 'CNY', 'USD', 'EUR', 'JPY', 'GBP');
        SET amount = ROUND(RAND() * 100000 + 100, 2);

        -- 货币转换（简化处理，实际应根据汇率）
        IF currency = 'CNY' THEN
            SET usd_amount = amount / 7.0;
            SET rmb_amount = amount;
        ELSEIF currency = 'USD' THEN
            SET usd_amount = amount;
            SET rmb_amount = amount * 7.0;
        ELSEIF currency = 'EUR' THEN
            SET usd_amount = amount * 1.1;
            SET rmb_amount = amount * 7.7;
        ELSE
            SET usd_amount = amount * 0.01;
            SET rmb_amount = amount * 0.07;
        END IF;

        -- 生成余额
        SET balance = ROUND(RAND() * 1000000 + 10000, 2);

        -- 随机选择业务类型
        SET settlement_type = ELT(FLOOR(1 + RAND() * 15),
            'ST001', 'ST002', 'ST003', 'ST004', 'ST005',
            'ST006', 'ST007', 'ST008', 'ST009', 'ST010',
            'ST011', 'ST012', 'ST013', 'ST014', 'ST015');

        -- 随机选择交易方式
        SET bank_flag = ELT(FLOOR(1 + RAND() * 5), '11', '12', '13', '14', '15');

        -- 生成交易用途
        SET purpose_desc = ELT(FLOOR(1 + RAND() * 20),
            '工资发放', '采购付款', '货款结算', '服务费', '租金支付',
            '投资收益', '还款', '转账', '消费', '提现',
            '报销费用', '捐赠', '保险费', '税费', '分红',
            '货款', '服务款', '咨询费', '差旅费', '其他费用');

        -- 插入交易记录
        INSERT INTO tb_acc_txn (
            Date, Time, Self_bank_code, Acc_type, Cst_no, Id_no,
            Self_acc_no, Card_no, Part_acc_no, Part_acc_name, Lend_flag,
            Tsf_flag, Cur, Org_amt, Usd_amt, Rmb_amt, Balance,
            Agency_flag, Reverse_flag, Purpose, Bord_flag, Bank_flag,
            Ip_code, Mac_info, Settle_type, Ticd
        ) VALUES (
            DATE_FORMAT(trans_date, '%Y%m%d'),
            DATE_FORMAT(trans_time, '%H%i%s'),
            selected_bank_code,
            selected_acc_type,
            selected_cst_no,
            selected_id_no,
            selected_acc_no,
            selected_card_no,
            CASE WHEN RAND() > 0.3 THEN CONCAT('PART', LPAD(FLOOR(RAND() * 100000), 6, '0')) ELSE NULL END,
            CASE WHEN RAND() > 0.4 THEN gen_chinese_name() ELSE NULL END,
            lend_flag,
            tsf_flag,
            currency,
            amount,
            usd_amount,
            rmb_amount,
            balance,
            ELT(FLOOR(1 + RAND() * 2), '11', '12'), -- Agency_flag
            '10', -- Reverse_flag (10=否)
            purpose_desc,
            CASE WHEN RAND() > 0.9 THEN '11' ELSE '12' END, -- Bord_flag (跨境标识)
            bank_flag,
            CASE WHEN bank_flag IN ('11', '12') AND RAND() > 0.5 THEN
                CONCAT(FLOOR(RAND() * 256), '.', FLOOR(RAND() * 256), '.', FLOOR(RAND() * 256), '.', FLOOR(RAND() * 256))
            ELSE NULL END,
            CASE WHEN bank_flag IN ('11', '12') AND RAND() > 0.6 THEN
                CONCAT(SUBSTRING('0123456789ABCDEF', FLOOR(1 + RAND() * 16), 1),
                       SUBSTRING('0123456789ABCDEF', FLOOR(1 + RAND() * 16), 1), ':',
                       SUBSTRING('0123456789ABCDEF', FLOOR(1 + RAND() * 16), 1),
                       SUBSTRING('0123456789ABCDEF', FLOOR(1 + RAND() * 16), 1), ':',
                       SUBSTRING('0123456789ABCDEF', FLOOR(1 + RAND() * 16), 1),
                       SUBSTRING('0123456789ABCDEF', FLOOR(1 + RAND() * 16), 1))
            ELSE NULL END,
            settlement_type,
            CONCAT('TXN', DATE_FORMAT(trans_date, '%Y%m%d'), LPAD(i, 6, '0'))
        );

        SET i = i + 1;

        -- 每1000条提交一次，避免内存问题
        IF i % 1000 = 0 THEN
            COMMIT;
        END IF;
    END WHILE;

END //
DELIMITER ;

-- 执行存储过程生成交易数据
CALL GenerateTransactions();

-- =====================================================
-- 第八部分: 插入风险等级数据
-- =====================================================

-- 为个人客户生成最新风险等级
INSERT INTO tb_risk_new (
    Bank_code1, Cst_no, Self_acc_name, Id_no, Acc_type,
    Risk_code, Time, Norm
)
SELECT
    p.Bank_code1,
    p.Cst_no,
    p.Acc_name,
    p.Id_no,
    '11' as Acc_type,
    ELT(FLOOR(1 + RAND() * 4), '10', '11', '12', '13') as Risk_code, -- 10=高, 11=中高, 12=中, 13=低
    DATE_FORMAT(DATE_SUB(CURRENT_DATE, INTERVAL FLOOR(RAND() * 30) DAY), '%Y%m%d') as Time,
    ELT(FLOOR(1 + RAND() * 5),
        '客户交易金额较大，资金往来频繁', '客户行业属于高风险行业', '客户为新开户客户',
        '客户资金来源不明，需要持续监控', '客户综合评分正常，风险较低') as Norm
FROM tb_cst_pers p;

-- 为企业客户生成最新风险等级
INSERT INTO tb_risk_new (
    Bank_code1, Cst_no, Self_acc_name, Id_no, Acc_type,
    Risk_code, Time, Norm
)
SELECT
    u.Bank_code1,
    u.Cst_no,
    u.Acc_name,
    u.License,
    '12' as Acc_type,
    ELT(FLOOR(1 + RAND() * 4), '10', '11', '12', '13') as Risk_code,
    DATE_FORMAT(DATE_SUB(CURRENT_DATE, INTERVAL FLOOR(RAND() * 30) DAY), '%Y%m%d') as Time,
    ELT(FLOOR(1 + RAND() * 5),
        '企业注册资本较高，交易规模大', '企业所属行业风险等级中等',
        '企业经营状况稳定，风险可控', '新成立企业，需要加强监控',
        '企业合规情况良好，风险较低') as Norm
FROM tb_cst_unit u;

-- 为部分客户生成历史风险等级记录（模拟风险等级变化）
INSERT INTO tb_risk_his (
    Bank_code1, Cst_no, Self_acc_name, Id_no, Acc_type,
    Risk_code, Time, Norm
)
SELECT
    Bank_code1,
    Cst_no,
    Self_acc_name,
    Id_no,
    Acc_type,
    ELT(FLOOR(1 + RAND() * 4), '10', '11', '12', '13') as Risk_code,
    DATE_FORMAT(DATE_SUB(CURRENT_DATE, INTERVAL FLOOR(RAND() * 365 + 30) DAY), '%Y%m%d') as Time,
    ELT(FLOOR(1 + RAND() * 3),
        '前期风险评估结果', '定期风险复评结果', '风险等级调整记录') as Norm
FROM tb_risk_new
WHERE RAND() > 0.6; -- 40%的客户有历史风险记录

-- =====================================================
-- 第九部分: 数据统计和验证
-- =====================================================

-- 显示数据生成统计
SELECT '数据生成统计报告' as report_type;

SELECT '个人客户数量' as item_type, COUNT(*) as count FROM tb_cst_pers;
SELECT '企业客户数量' as item_type, COUNT(*) as count FROM tb_cst_unit;
SELECT '账户数量' as item_type, COUNT(*) as count FROM tb_acc WHERE Acc_state = '11';
SELECT '交易记录数量' as item_type, COUNT(*) as count FROM tb_acc_txn;
SELECT '最新风险等级记录' as item_type, COUNT(*) as count FROM tb_risk_new;
SELECT '历史风险等级记录' as item_type, COUNT(*) as count FROM tb_risk_his;

-- 风险等级分布统计
SELECT
    '个人客户风险等级分布' as distribution_type,
    CASE Risk_code
        WHEN '10' THEN '高风险'
        WHEN '11' THEN '中高风险'
        WHEN '12' THEN '中等风险'
        WHEN '13' THEN '低风险'
    END as risk_level,
    COUNT(*) as customer_count
FROM tb_risk_new WHERE Acc_type = '11'
GROUP BY Risk_code;

SELECT
    '企业客户风险等级分布' as distribution_type,
    CASE Risk_code
        WHEN '10' THEN '高风险'
        WHEN '11' THEN '中高风险'
        WHEN '12' THEN '中等风险'
        WHEN '13' THEN '低风险'
    END as risk_level,
    COUNT(*) as customer_count
FROM tb_risk_new WHERE Acc_type = '12'
GROUP BY Risk_code;

-- 交易统计
SELECT
    '交易金额统计' as statistic_type,
    COUNT(*) as total_transactions,
    ROUND(AVG(Org_amt), 2) as avg_amount,
    ROUND(MAX(Org_amt), 2) as max_amount,
    ROUND(MIN(Org_amt), 2) as min_amount,
    ROUND(SUM(Org_amt), 2) as total_amount
FROM tb_acc_txn;

-- 启用外键检查
SET FOREIGN_KEY_CHECKS = 1;

-- =====================================================
-- 程序执行完成提示
-- =====================================================

SELECT 'AML-EDD反洗钱数据库建表和数据生成程序执行完成！' as completion_message;
SELECT '生成的数据规模：1000个个人客户，100个企业客户，约10000条交易记录' as scale_info;
SELECT '数据库编码：UTF-8，完全支持简体中文' as encoding_info;
SELECT '符合农业银行300号文件接口格式要求' as compliance_info;

-- 最终优化建议
SELECT '建议执行以下后续操作：' as suggestions;
SELECT '1. 执行 ANALYZE TABLE 优化表统计信息' as suggestion1;
SELECT '2. 根据实际业务需求调整索引策略' as suggestion2;
SELECT '3. 配置适当的备份策略' as suggestion3;
SELECT '4. 设置数据安全访问权限' as suggestion4;